# Generated by Django 4.1.1 on 2023-02-23 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0005_remove_category_posts_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
