# Generated by Django 4.1.3 on 2023-02-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0007_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='categories', to='blogging.post'),
        ),
    ]
